# Build and Deploy CV to GitHub Pages
name: Build and Deploy CV

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Edit here with the names of your latex file and directory (can use ".")
      DIR: .
      FILE: cv
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX CV
        uses: dante-ev/latex-action@latest
        with:
          root_file: ${{ env.FILE }}
          working_directory: ${{ env.DIR }}

      - name: Prepare artifacts
        run: |
          mkdir -p github_artifacts
          cp ${{ env.DIR }}/${{ env.FILE }}.pdf ./github_artifacts/
          cp index.html ./github_artifacts/

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.FILE }}.pdf
          path: ./github_artifacts
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: github_artifacts

      - name: Prepare deployment files
        run: |
          mkdir -p github_deploy
          mv github_artifacts/*/* github_deploy
          # Ensure index.html is present
          if [ ! -f github_deploy/index.html ]; then
            cp index.html github_deploy/
          fi
          ls -la github_deploy/

      - name: Deploy to GitHub Pages (build branch)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github_deploy
          publish_branch: build
          force_orphan: true
          commit_message: "Deploy CV: ${{ github.sha }}"
          enable_jekyll: true
  copy-index-to-build:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Copy To Branches Action
        uses: planetoftheweb/copy-to-branches@v1.3
        env:
          key: main
          files: index.html CNAME
